### ISSUE TITLE
Infinite loop ?

### ISSUE THREAD

**Issue by Zardoz89** [MadMockers/BareBonesOS#12]
https://github.com/MadMockers/BareBonesOS/blob/master/src/video.asm#L133

```
.scrollscreen:
    SET PUSH, [Z+0]
        JSR scrollscreen
    ADD SP, 1
```

**Comment by MadMockers** [comment]
Poorly named labels.

The first one is a local label, since it starts with a '.'. The previous non local label is 'video_irq', so '.scrollscreen' is similar to naming the label 'video_irq.scrollscreen'

The 'scrollscreen' in the JSR is a global label, and jumps to here: https://github.com/MadMockers/BareBonesOS/blob/master/src/bbos.asm#L374
