### ISSUE TITLE
Interrupt Asynchronicity

### ISSUE THREAD

**Issue by interfect** [MadMockers/BareBonesOS#4]
The DCPU has interrupt queueing. Only one interrupt can be processed off the queue between any two instructions, and a new interrupt can't be processed while an interrupt is already being processed.

The upshot of this seems to be that if there are a bunch of interrupts in the queue, when you call an `INT` instruction, that interrupt might get queued. Some other interrupt will execute off of the queue before your next user instruction executes, and your user code may proceed on, thinking the interrupt you called had returned, when in fact the interrupt you generated might not happen until two or three instructions later. (Depending on your emulator; some may let `INT` interrupts jump to the front of the queue, because they think the alternative is pretty dumb.)

This can cause problems when you call a BBOS function via interrupt: if your user code moves on immediately, BBOS, when it finally runs, may read the wrong values as arguments, and user code may read some arbitrary value as an output value before BBOS has had a chance to actually return.

In order to work around this edge case, what you could do is have some kind of synchronization flag. The user code would set up the arguments, reset the flag, and `INT` into BBOS. It would then wait for the flag to be set again, indicating that the BBOS interrupt handler had actually gotten a chance to run. (Something like `SUB PC, A` would work, if A = 0 meant BBOS had run. If the flag is in RAM it gets a bit harder.)

Alternately, you could just declare that emulators that want to run BBOS correctly need to have `INT` queue jumping, or that you aren't allowed to make a BBOS call if a device is able to send an interrupt.

**Comment by MadMockers** [comment]
I'm not too sure what to do about this. My emulator implementation doesn't force an instruction to happen between 2 interrupts (i.e, if 5 interrupts are queued, they all happen). This is as you point out contrary to "The DCPU-16 will perform at most one interrupt between each instruction." from the official specification.

There are a number different solutions that I can see. I'll list the ones that don't modify the DCPU spec first:
- As you suggest, have some sort of flag with a loop. I feel this is not a very nice option as it greatly increases the code required to make a BBOS call.
- Use the BBOS 'get info' call (A = 0) to call the API_Handler as is described in the README.txt here: https://github.com/MadMockers/BareBonesOS/blob/master/README.txt#L77 . This way BBOS calls take the form of a JSR instead of an INT.

Using INT to call BBOS Get Info should be done before any hardware is initialized. At this point in time BBOS doesn't cause hardware to generate interrupts before it is used, and thus as long as the first thing BBOS dependant software does is Get Info, there shouldn't be an issue with multiple interrupts.

Options that do modify the spec:
- As you suggest, have software interrupts jump to the front of the interrupt queue
- As my emulator is implemented, have no limit on the number of interrupts between instructions.

My ideal solution would be how my emulator currently does interrupts, as I believe this makes the most sense. I feel not having this approach as the implementation actually makes the software INT opcode essentially useless. I'll have to talk to @paultech to see if he is open to changing the DCPU spec to allow for this. Otherwise I'm essentially forced to deprecate the INT method of calling (after the first BBOS get info call).

**Comment by Zardoz89** [comment]
On the TR3200 specs&implementation I ended setting that software interrupts have higher priority. Ie, jumps to the front of the interrupt queue.
It's simple, and just works nice (plus is how on the Real World TM this things works).

Eventually, you would be pushed to tweak DCPU specs. Notch stopped of changing it, because he focused on the game engine.

**Comment by paultech** [comment]
Speaking to a few people in the IRC channel everyone favors "have software interrupts jump to the front of the interrupt queue". I will work with the team to publish our new DCPU spec that documents the emulator and assembler.

**Comment by MadMockers** [comment]
This change will leave BBOS working as is, so I'll close this issue.

Go team!
